CREATE DATABASE IF NOT EXISTS cadastros;
USE cadastros;

CREATE TABLE pessoas (NOME VARCHAR(100), IDADE VARCHAR(2), ALTURA VARCHAR(3), PESO_KG VARCHAR(3));
	INSERT INTO pessoas VALUES ("Fulano de Tal", "32", "178", "100");
